### ISSUE TITLE
HookWebpackError: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by doshigo** [Civil-Cultural/civil-cultural#5]
Ao tentar rodar o script `npm run-script build` gerou o seguinte erro

```
HookWebpackError: error:0308010C:digital envelope routines::unsupported
    at makeWebpackError (C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\webpack\bundle5.js:45539:9)
    at C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\webpack\bundle5.js:29467:12    
    at eval (eval at create (C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\webpack\bundle5.js:140927:10), <anonymous>:91:1)
-- inner error --
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at getHashDigest (C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\loader-utils\index.js:1:29141)
    at C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\loader-utils\index.js:1:31472  
    at String.replace (<anonymous>)
    at Object.interpolateName (C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\loader-utils\index.js:1:31381)
    at C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\build\webpack\plugins\copy-file-plugin.js:41:51
caused by plugins in Compilation.hooks.processAssets
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\loader-utils\index.js:1:31472  
    at String.replace (<anonymous>)
    at Object.interpolateName (C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\compiled\loader-utils\index.js:1:31381)
    at C:\Users\Hiago Silvério\Desktop\CivilCultural\civil-cultural\node_modules\next\dist\build\webpack\plugins\copy-file-plugin.js:41:51


> Build failed because of webpack errors
```

Verifiquei a resposta através do stackoverflow

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

```
On Unix-like (Linux, macOS, Git bash, etc.):
export NODE_OPTIONS=--openssl-legacy-provider

On Windows command prompt:
set NODE_OPTIONS=--openssl-legacy-provider

On PowerShell:
$env:NODE_OPTIONS = "--openssl-legacy-provider"
```

No ambiente windows setei o `$env:NODE_OPTIONS = "--openssl-legacy-provider"` no terminal do VS code e rodei novamente o comando resolveu o problema.

**Comment by marcio1002** [comment]
Obrigado pela resolução Doshigo
